#!/usr/bin/env -S deno run --unstable-bundle --allow-read --allow-write --allow-net
// deno-lint-ignore-file no-console
/**
 * Build script for the Puck plugin.
 *
 * This script:
 * 1. Bundles the client-side React code with `Deno.bundle()`
 * 2. Outputs to dist/puck-editor.js for serving
 * 3. Embeds the bundle as a TypeScript constant for JSR publishing
 *
 * Usage:
 *   deno task build:puck
 */

const PLUGIN_DIR = new URL('./', import.meta.url).pathname;
const CLIENT_ENTRY = `${PLUGIN_DIR}client/main.tsx`;
const DIST_DIR = `${PLUGIN_DIR}dist`;
const DIST_FILE = `${DIST_DIR}/puck-editor.js`;
const EMBEDDED_FILE = `${PLUGIN_DIR}bundle-embedded.ts`;

// Ensure dist directory exists
try {
  await Deno.mkdir(DIST_DIR, { recursive: true });
} catch {
  // Already exists
}

// Bundle using the programmatic API (Deno 2.4+)
console.log('Bundling client code...');
const result = await Deno.bundle({
  entrypoints: [CLIENT_ENTRY],
  platform: 'browser',
  minify: true,
});

if (!result.success) {
  console.error('Bundle failed:', result.errors);
  Deno.exit(1);
}

// Get the bundle content from the first output file
const bundleContent = result.outputFiles[0].text();
console.log(`Bundle size: ${(bundleContent.length / 1024).toFixed(2)} KB`);

// Write to dist folder for serving
await Deno.writeTextFile(DIST_FILE, bundleContent);
console.log(`Bundle written to: ${DIST_FILE}`);

// Generate embedded TypeScript file (for JSR publishing without file system)
const embeddedContent = `// AUTO-GENERATED - DO NOT EDIT
// Generated by: deno task build:puck
// Source: packages/plugins/puck/client/main.tsx

/**
 * Pre-bundled Puck editor client code.
 * This is embedded so the plugin works without file system access.
 */
export const PUCK_BUNDLE_JS = ${JSON.stringify(bundleContent)};

/**
 * Bundle content length in bytes.
 */
export const PUCK_BUNDLE_SIZE = ${bundleContent.length};
`;

await Deno.writeTextFile(EMBEDDED_FILE, embeddedContent);
console.log(`Embedded bundle written to: ${EMBEDDED_FILE}`);

// Also fetch the CSS (for embedding)
const puckCssUrl = 'https://esm.sh/@puckeditor/core@0.21.1/puck.css';
console.log(`Fetching Puck CSS from: ${puckCssUrl}`);
const cssRes = await fetch(puckCssUrl);
if (cssRes.ok) {
  let cssContent = await cssRes.text();

  // Strip external font import for privacy (avoid requests to rsms.me).
  // Puck's --puck-font-family has fallback fonts defined, so the UI still looks fine.
  cssContent = cssContent.replace(
    /@import\s+["']https:\/\/rsms\.me\/inter\/inter\.css["'];\s*/g,
    '/* @import removed for privacy - Inter font loads from rsms.me */\n',
  );

  // Write to dist for serving
  await Deno.writeTextFile(`${DIST_DIR}/puck.css`, cssContent);
  console.log(`CSS written to: ${DIST_DIR}/puck.css`);

  // Embed for JSR
  const cssEmbeddedFile = `${PLUGIN_DIR}css-embedded.ts`;
  const cssEmbedded = `// AUTO-GENERATED - DO NOT EDIT
// Fetched from: ${puckCssUrl}

/**
 * Pre-fetched Puck CSS styles.
 */
export const PUCK_CSS = ${JSON.stringify(cssContent)};
`;
  await Deno.writeTextFile(cssEmbeddedFile, cssEmbedded);
  console.log(
    `Embedded CSS written to: ${cssEmbeddedFile} (${
      (cssContent.length / 1024).toFixed(2)
    } KB)`,
  );
}

console.log('Build complete!');
