/**
 * Puck Editor Plugin for HotSauce CMS
 *
 * Adds "Edit with Puck" links to columns marked with `.$cms({ plugins: { puck: true } })`
 * and provides routes for the Puck visual editor UI.
 *
 * The plugin bundles React + Puck and serves them automatically.
 * Users only need to provide their own components bundle.
 *
 * @example
 * ```ts
 * import { createPuckPlugin } from '@hotsauce/plugins/puck';
 *
 * const handler = createCmsHandler({
 *   // ...
 *   plugins: [createPuckPlugin({
 *     basePath: '/admin',
 *     componentsJs: '/admin/components.js',
 *   })],
 * });
 * ```
 *
 * @module
 */

import type { InProcessPluginConfig, PluginRouteContext } from '@hotsauce/cms';
import { escapeHtml } from '@hotsauce/ui';

// Embedded bundles (generated by deno task build:puck)
import { PUCK_BUNDLE_JS } from './bundle-embedded.ts';
import { PUCK_CSS } from './css-embedded.ts';

// Re-export types for convenience
export type { InProcessPluginConfig, PluginRouteContext };

/** Editor page layout CSS (served as external stylesheet) */
const PUCK_EDITOR_CSS = `\
* { box-sizing: border-box; }
body { font-family: system-ui, -apple-system, sans-serif; margin: 0; padding: 0; background: #f5f5f5; }
#puck-root { min-height: 100vh; }
`;

/**
 * Configuration options for the Puck plugin.
 */
export interface PuckPluginOptions {
  /**
   * Base path of the CMS admin (e.g., '/admin').
   * Used for generating editor URLs and back links.
   */
  basePath: string;

  /**
   * URL to the user's components bundle (ES module).
   * This bundle must export `config` - a full Puck Config object with:
   * - `components`: Object mapping component names to definitions
   * - `root` (optional): Root configuration with fields and render for page-level data
   *
   * Components should use `globalThis.React` provided by the editor bundle.
   *
   * @example '/admin/components.js'
   */
  componentsJs: string;

  /**
   * Optional URL to CSS for user components.
   * Puck's CSS is automatically included; use this for custom component styles.
   *
   * @example '/admin/components.css'
   */
  componentsCss?: string;
}

function safeJsonForInlineHtml(value: unknown): string {
  // Prevent breaking out of <script type="application/json"> and avoid HTML parsing quirks.
  return JSON.stringify(value)
    .replaceAll('&', '\\u0026')
    .replaceAll('<', '\\u003c')
    .replaceAll('>', '\\u003e');
}

/**
 * Render the Puck editor page HTML.
 */
function renderEditorPage(
  ctx: PluginRouteContext,
  opts: PuckPluginOptions,
): string {
  const {
    table,
    recordId,
    column,
    value,
    basePath,
    csrfToken,
    sourceToken,
  } = ctx;

  // Parse initial Puck data from column value.
  // Puck expects: { content: [], root: { props: {} }, zones?: {} }
  const emptyPuckData = { content: [], root: { props: {} } };
  let initialPuckData: unknown = emptyPuckData;
  if (typeof value === 'string') {
    try {
      const parsed = JSON.parse(value);
      if (
        parsed && typeof parsed === 'object' && Array.isArray(parsed.content)
      ) {
        initialPuckData = parsed;
      }
    } catch {
      // Keep empty state
    }
  } else if (
    value && typeof value === 'object' &&
    Array.isArray((value as Record<string, unknown>).content)
  ) {
    initialPuckData = value;
  }

  // Fixed paths for embedded bundles served by this plugin
  const editorBundleUrl = `${opts.basePath}/puck/_assets/puck-editor.js`;
  const puckCssUrl = `${opts.basePath}/puck/_assets/puck.css`;
  const puckEditorCssUrl = `${opts.basePath}/puck/_assets/puck-editor.css`;
  const componentsCssLink = opts.componentsCss
    ? `<link rel="stylesheet" href="${opts.componentsCss}">`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Puck Editor - ${escapeHtml(table)}/${escapeHtml(recordId)}/${
    escapeHtml(column ?? '')
  }</title>
  <link rel="stylesheet" href="${puckCssUrl}">
  <link rel="stylesheet" href="${puckEditorCssUrl}">
  ${componentsCssLink}
</head>
<body>
  <div id="puck-root"></div>
  <script type="application/json" id="puck-config">${
    safeJsonForInlineHtml({
      componentsUrl: opts.componentsJs,
      table,
      recordId,
      column,
      csrfToken,
      sourceToken,
      basePath,
      data: initialPuckData,
    })
  }</script>
  <script type="module" src="${editorBundleUrl}"></script>
</body>
</html>`;
}

/**
 * Create a Puck editor plugin for the CMS.
 *
 * This plugin:
 * 1. Serves the bundled React + Puck editor at `/_assets/puck-editor.js`
 * 2. Serves Puck CSS at `/_assets/puck.css`
 * 3. Adds "Edit with Puck" links to columns marked with `.$cms({ plugins: { puck: true } })`
 * 4. Provides routes for the Puck editor UI at `/admin/puck/:table/:id/:column`
 *
 * @param options - Plugin configuration options
 * @returns Plugin configuration to pass to `createCmsHandler`
 *
 * @example
 * ```ts
 * // In your schema:
 * export const pages = pgTable('pages', {
 *   id: serial('id').primaryKey(),
 *   content: jsonb('content').$cms({ plugins: { puck: true } }),
 * });
 *
 * // In your CMS setup:
 * import { createPuckPlugin } from '@hotsauce/plugins/puck';
 *
 * const handler = createCmsHandler({
 *   db,
 *   schema,
 *   plugins: [createPuckPlugin({
 *     basePath: '/admin',
 *     componentsJs: '/admin/components.js',
 *   })],
 * });
 * ```
 */
export function createPuckPlugin(
  options: PuckPluginOptions,
): InProcessPluginConfig {
  const opts = options;

  return {
    name: 'puck',
    description: 'Puck visual editor for JSON content columns',
    filter: (ctx) => {
      // Allow UI hooks for any table with puck-enabled columns
      if (ctx.hookType === 'ui:renderField') return true;
      // Allow route handlers
      if (ctx.hookType === 'route') return true;
      return false;
    },
    hooks: {
      ui: {
        renderField: (ctx) => {
          // ctx.field.plugin is set if column has .$cms({ plugins: { puck: ... } })
          if (ctx.field.plugin && ctx.recordId) {
            const href =
              `${opts.basePath}/puck/${ctx.table}/${ctx.recordId}/${ctx.field.name}`;

            // Parse Puck data to generate summary
            let valueSummary = '0 blocks';
            if (ctx.value && typeof ctx.value === 'object') {
              const data = ctx.value as { content?: unknown[] };
              const count = data.content?.length ?? 0;
              valueSummary = count === 1 ? '1 block' : `${count} blocks`;
            }

            return {
              link: { href, label: 'Edit with Puck', target: '_blank' },
              valueSummary,
            };
          }
          return null;
        },
      },
    },
    routes: [
      // Serve embedded Puck editor bundle (React + Puck)
      {
        pattern: '_assets/puck-editor.js',
        methods: ['GET'],
        handler: () =>
          new Response(PUCK_BUNDLE_JS, {
            headers: {
              'Content-Type': 'application/javascript; charset=utf-8',
            },
          }),
      },
      // Serve embedded Puck CSS
      {
        pattern: '_assets/puck.css',
        methods: ['GET'],
        handler: () =>
          new Response(PUCK_CSS, {
            headers: { 'Content-Type': 'text/css; charset=utf-8' },
          }),
      },
      // Serve editor page CSS (layout reset)
      {
        pattern: '_assets/puck-editor.css',
        methods: ['GET'],
        handler: () =>
          new Response(PUCK_EDITOR_CSS, {
            headers: { 'Content-Type': 'text/css; charset=utf-8' },
          }),
      },
      // Editor page
      {
        pattern: ':table/:id/:column',
        methods: ['GET'],
        handler: (ctx) => renderEditorPage(ctx, opts),
        csp: { styleSrc: ["'unsafe-inline'"] },
      },
    ],
  };
}
