/**
 * Puck Editor Plugin for HotSauce CMS
 *
 * Adds "Edit with Puck" links to columns marked with `.$cms({ plugins: { puck: true } })`
 * and provides routes for the Puck visual editor UI.
 *
 * @example
 * ```ts
 * import { createPuckPlugin } from '@hotsauce/plugins/puck';
 *
 * const handler = createCmsHandler({
 *   // ...
 *   plugins: [createPuckPlugin('/admin')],
 * });
 * ```
 *
 * @module
 */

import type { InProcessPluginConfig, PluginRouteContext } from '@hotsauce/cms';
import { escapeHtml } from '@hotsauce/ui';

// Import embedded bundle and CSS (generated by build.ts)
import { PUCK_BUNDLE_JS } from './bundle-embedded.ts';
import { PUCK_CSS } from './css-embedded.ts';

// Re-export types for convenience
export type { InProcessPluginConfig, PluginRouteContext };

/**
 * Configuration options for the Puck plugin.
 */
export interface PuckPluginOptions {
  /**
   * Base path of the CMS admin (e.g., '/admin').
   * Used for generating editor URLs and back links.
   */
  basePath: string;
}

function safeJsonForInlineHtml(value: unknown): string {
  // Prevent breaking out of <script type="application/json"> and avoid HTML parsing quirks.
  return JSON.stringify(value)
    .replaceAll('&', '\\u0026')
    .replaceAll('<', '\\u003c')
    .replaceAll('>', '\\u003e');
}

/**
 * Default Puck component configuration.
 * Users can override this via plugin config in the future.
 */
const DEFAULT_PUCK_CONFIG = {
  components: {
    HeadingBlock: {
      fields: {
        children: { type: 'text' },
      },
    },
  },
};

/**
 * Render the Puck editor page HTML.
 */
function renderEditorPage(
  ctx: PluginRouteContext,
  opts: PuckPluginOptions,
): string {
  const {
    table,
    recordId,
    column,
    value,
    field,
    basePath,
    csrfToken,
    sourceToken,
  } = ctx;

  // Parse initial Puck data from column value.
  // Puck expects: { content: [], root: { props: {} }, zones?: {} }
  const emptyPuckData = { content: [], root: { props: {} } };
  let initialPuckData: unknown = emptyPuckData;
  if (typeof value === 'string') {
    try {
      const parsed = JSON.parse(value);
      if (
        parsed && typeof parsed === 'object' && Array.isArray(parsed.content)
      ) {
        initialPuckData = parsed;
      }
    } catch {
      // Keep empty state
    }
  } else if (
    value && typeof value === 'object' &&
    Array.isArray((value as Record<string, unknown>).content)
  ) {
    initialPuckData = value;
  }

  const puckConfig = DEFAULT_PUCK_CONFIG;

  // Bundle and CSS are served from plugin routes
  const bundleUrl = `${opts.basePath}/puck/_assets/bundle.js`;
  const cssUrl = `${opts.basePath}/puck/_assets/puck.css`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Puck Editor - ${escapeHtml(table)}/${escapeHtml(recordId)}/${
    escapeHtml(column ?? '')
  }</title>
  <link rel="stylesheet" href="${cssUrl}">
  <script type="application/json" id="puck-bootstrap">${
    safeJsonForInlineHtml({
      table,
      recordId,
      column,
      csrfToken,
      sourceToken,
      basePath,
      config: puckConfig,
      data: initialPuckData,
    })
  }</script>
  <script type="module" src="${bundleUrl}"></script>
  <style>
    * { box-sizing: border-box; }
    body { 
      font-family: system-ui, -apple-system, sans-serif; 
      margin: 0; 
      padding: 0;
      background: #f5f5f5;
    }
    #puck-root {
      min-height: 100vh;
    }
    #puck-error {
      background: #fff3e0;
      border: 1px solid #ffb74d;
      border-radius: 4px;
      padding: 15px;
      margin: 20px;
    }
    .debug-panel {
      position: fixed;
      bottom: 0;
      left: 0;
      right: 0;
      background: rgba(0,0,0,0.9);
      color: #fff;
      padding: 10px;
      font-family: monospace;
      font-size: 12px;
      max-height: 200px;
      overflow: auto;
      z-index: 10000;
      display: none;
    }
  </style>
</head>
<body>
  <div id="puck-error" style="display:none"></div>
  <div id="puck-root"></div>
  
  <!-- Debug panel (hidden by default, toggle with Ctrl+Shift+D) -->
  <div class="debug-panel" id="debug-panel">
    <strong>Debug Info:</strong>
    <pre>Table: ${escapeHtml(table)}
Record: ${escapeHtml(recordId)}
Column: ${escapeHtml(column ?? 'N/A')}
Field Type: ${escapeHtml(field?.type ?? 'unknown')}
CSRF: ${escapeHtml(csrfToken.slice(0, 8))}...</pre>
  </div>
  <script>
    // Toggle debug panel with Ctrl+Shift+D
    document.addEventListener('keydown', (e) => {
      if (e.ctrlKey && e.shiftKey && e.key === 'D') {
        const panel = document.getElementById('debug-panel');
        panel.style.display = panel.style.display === 'none' ? 'block' : 'none';
      }
    });
  </script>
</body>
</html>`;
}

/**
 * Create a Puck editor plugin for the CMS.
 *
 * This plugin:
 * 1. Adds "Edit with Puck" links to columns marked with `.$cms({ plugins: { puck: true } })`
 * 2. Provides routes for the Puck editor UI at `/admin/puck/:table/:id/:column`
 *
 * @param options - Plugin configuration options
 * @returns Plugin configuration to pass to `createCmsHandler`
 *
 * @example
 * ```ts
 * // In your schema:
 * export const pages = pgTable('pages', {
 *   id: serial('id').primaryKey(),
 *   content: jsonb('content').$cms({ plugins: { puck: true } }),
 * });
 *
 * // In your CMS setup:
 * import { createPuckPlugin } from '@hotsauce/plugins/puck';
 *
 * const handler = createCmsHandler({
 *   db,
 *   schema,
 *   plugins: [createPuckPlugin({ basePath: '/admin' })],
 * });
 * ```
 */
export function createPuckPlugin(
  options: PuckPluginOptions | string,
): InProcessPluginConfig {
  // Support simple string arg for backwards compatibility
  const opts: PuckPluginOptions = typeof options === 'string'
    ? { basePath: options }
    : options;

  return {
    name: 'puck',
    description: 'Puck visual editor for JSON content columns',
    filter: (ctx) => {
      // Allow UI hooks for any table with puck-enabled columns
      if (ctx.hookType === 'ui:renderField') return true;
      // Allow route handlers
      if (ctx.hookType === 'route') return true;
      return false;
    },
    hooks: {
      ui: {
        renderField: (ctx) => {
          // ctx.field.plugin is set if column has .$cms({ plugins: { puck: ... } })
          if (ctx.field.plugin && ctx.recordId) {
            const href =
              `${opts.basePath}/puck/${ctx.table}/${ctx.recordId}/${ctx.field.name}`;

            // Parse Puck data to generate summary
            let valueSummary = '0 blocks';
            if (ctx.value && typeof ctx.value === 'object') {
              const data = ctx.value as { content?: unknown[] };
              const count = data.content?.length ?? 0;
              valueSummary = count === 1 ? '1 block' : `${count} blocks`;
            }

            return {
              link: { href, label: 'Edit with Puck', target: '_blank' },
              valueSummary,
            };
          }
          return null;
        },
      },
    },
    routes: [
      // Static assets - must come before dynamic routes
      {
        pattern: '_assets/bundle.js',
        methods: ['GET'],
        handler: () =>
          new Response(PUCK_BUNDLE_JS, {
            headers: {
              'Content-Type': 'application/javascript; charset=utf-8',
              'Cache-Control': 'public, max-age=31536000, immutable',
            },
          }),
      },
      {
        pattern: '_assets/puck.css',
        methods: ['GET'],
        handler: () =>
          new Response(PUCK_CSS, {
            headers: {
              'Content-Type': 'text/css; charset=utf-8',
              'Cache-Control': 'public, max-age=31536000, immutable',
            },
          }),
      },
      // Editor page
      {
        pattern: ':table/:id/:column',
        methods: ['GET'],
        handler: (ctx) => renderEditorPage(ctx, opts),
      },
    ],
  };
}
